package handlers

import (
	"html"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
)

var shareIDPattern = regexp.MustCompile(`^[a-f0-9-]{36}$`)

// NewShareHandler serves permanent oracle readings and their raw markdown files.
func NewShareHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
			return
		}

		name := path.Base(strings.TrimPrefix(r.URL.Path, "/api/share/"))
		wantsMarkdown := strings.HasSuffix(name, ".md")
		id := strings.TrimSuffix(name, ".md")
		if !shareIDPattern.MatchString(id) {
			http.NotFound(w, r)
			return
		}

		markdown, err := os.ReadFile(filepath.Join(readingStoreDir, id+".md"))
		if err != nil {
			http.NotFound(w, r)
			return
		}

		if wantsMarkdown {
			w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
			_, _ = w.Write(markdown)
			return
		}

		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write([]byte(renderShareHTML(string(markdown), r.URL.Path+".md")))
	})
}

// renderShareHTML creates a small standalone page for sharing with friends.
func renderShareHTML(markdown string, markdownURL string) string {
	return `<!doctype html>
<html lang="de">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>CoffeeOracle Lesung</title>
  <style>
    body { margin: 0; background: #0f0603; color: #fff9f2; font-family: system-ui, sans-serif; }
    main { max-width: 760px; margin: 0 auto; padding: 32px 18px 48px; }
    article { border: 1px solid rgba(255,255,255,.12); border-radius: 28px; background: rgba(45,20,13,.78); padding: 24px; box-shadow: 0 35px 120px rgba(12,5,3,.55); }
    img { display: block; width: 100%; max-height: 420px; object-fit: cover; border-radius: 18px; margin: 18px 0; }
    a { color: #f4d9b2; }
    p { line-height: 1.65; }
    pre { white-space: pre-wrap; line-height: 1.65; font: inherit; }
  </style>
</head>
<body>
  <main>
    <article>` + markdownToHTML(markdown) + `<p><a href="` + html.EscapeString(markdownURL) + `">Markdown herunterladen</a></p></article>
  </main>
</body>
</html>`
}

// markdownToHTML renders the subset of Markdown generated by this app.
func markdownToHTML(markdown string) string {
	var out strings.Builder
	for _, line := range strings.Split(markdown, "\n") {
		trimmed := strings.TrimSpace(line)
		switch {
		case trimmed == "":
			continue
		case strings.HasPrefix(trimmed, "!["):
			start := strings.Index(trimmed, "](")
			if start > 0 && strings.HasSuffix(trimmed, ")") {
				alt := strings.TrimPrefix(trimmed[:start], "![")
				src := strings.TrimSuffix(trimmed[start+2:], ")")
				out.WriteString(`<img src="` + html.EscapeString(src) + `" alt="` + html.EscapeString(alt) + `" />`)
			}
		case strings.HasPrefix(trimmed, "# "):
			out.WriteString("<h1>" + html.EscapeString(strings.TrimPrefix(trimmed, "# ")) + "</h1>")
		case strings.HasPrefix(trimmed, "## "):
			out.WriteString("<h2>" + html.EscapeString(strings.TrimPrefix(trimmed, "## ")) + "</h2>")
		default:
			out.WriteString("<p>" + html.EscapeString(trimmed) + "</p>")
		}
	}
	return out.String()
}
