package handlers

import (
	"html"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
)

var shareIDPattern = regexp.MustCompile(`^[a-f0-9-]{36}$`)
var boldPattern = regexp.MustCompile(`\*\*(.*?)\*\*`)

// NewShareHandler serves permanent oracle readings and their raw markdown files.
func NewShareHandler() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			http.Error(w, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
			return
		}

		name := path.Base(strings.TrimPrefix(r.URL.Path, "/api/share/"))
		wantsMarkdown := strings.HasSuffix(name, ".md")
		id := strings.TrimSuffix(name, ".md")
		if !shareIDPattern.MatchString(id) {
			http.NotFound(w, r)
			return
		}

		markdown, err := os.ReadFile(filepath.Join(readingStoreDir, id+".md"))
		if err != nil {
			http.NotFound(w, r)
			return
		}

		if wantsMarkdown {
			w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
			_, _ = w.Write(markdown)
			return
		}

		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write([]byte(renderShareHTML(string(markdown), r.URL.Path+".md")))
	})
}

// renderShareHTML creates a small standalone page for sharing with friends.
func renderShareHTML(markdown string, markdownURL string) string {
	return `<!doctype html>
<html lang="de">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>CoffeeOracle Lesung</title>
  <style>
    body { margin: 0; background: #0f0603; color: #fff9f2; font-family: system-ui, sans-serif; }
    main { max-width: 760px; margin: 0 auto; padding: 32px 18px 48px; }
    article { border: 1px solid rgba(255,255,255,.12); border-radius: 28px; background: rgba(45,20,13,.78); padding: 24px; box-shadow: 0 35px 120px rgba(12,5,3,.55); }
    img { display: block; width: 100%; max-height: 420px; object-fit: cover; border-radius: 18px; margin: 18px 0; }
    a { color: #f4d9b2; }
    p { line-height: 1.65; }
    pre { white-space: pre-wrap; line-height: 1.65; font: inherit; }
    h1, h2, h3, h4 { margin-top: 1.5em; margin-bottom: 0.5em; }
    ul { padding-left: 20px; line-height: 1.65; margin: 12px 0; }
    li { margin-bottom: 6px; }
    strong { color: #f4d9b2; }
    blockquote { border-left: 4px solid rgba(244,217,178,0.5); padding-left: 16px; margin-left: 0; font-style: italic; color: rgba(255,249,242,0.8); }
  </style>
</head>
<body>
  <main>
    <article>` + markdownToHTML(markdown) + `<p><a href="` + html.EscapeString(markdownURL) + `">Markdown herunterladen</a></p></article>
  </main>
</body>
</html>`
}

// renderInline escapes HTML and applies basic inline markdown like bold.
func renderInline(text string) string {
	escaped := html.EscapeString(text)
	return boldPattern.ReplaceAllString(escaped, "<strong>$1</strong>")
}

// markdownToHTML renders the subset of Markdown generated by this app.
func markdownToHTML(markdown string) string {
	var out strings.Builder
	inList := false

	closeList := func() {
		if inList {
			out.WriteString("</ul>")
			inList = false
		}
	}

	for _, line := range strings.Split(markdown, "\n") {
		trimmed := strings.TrimSpace(line)

		if trimmed == "" {
			closeList()
			continue
		}

		if strings.HasPrefix(trimmed, "!") {
			closeList()
			start := strings.Index(trimmed, "](")
			if start > 0 && strings.HasSuffix(trimmed, ")") {
				alt := strings.TrimPrefix(trimmed[:start], "![")
				src := strings.TrimSuffix(trimmed[start+2:], ")")
				out.WriteString(`<img src="` + html.EscapeString(src) + `" alt="` + html.EscapeString(alt) + `" />`)
			}
			continue
		}
		if strings.HasPrefix(trimmed, "# ") {
			closeList()
			out.WriteString("<h1>" + renderInline(strings.TrimPrefix(trimmed, "# ")) + "</h1>")
			continue
		}
		if strings.HasPrefix(trimmed, "## ") {
			closeList()
			out.WriteString("<h2>" + renderInline(strings.TrimPrefix(trimmed, "## ")) + "</h2>")
			continue
		}
		if strings.HasPrefix(trimmed, "### ") {
			closeList()
			out.WriteString("<h3>" + renderInline(strings.TrimPrefix(trimmed, "### ")) + "</h3>")
			continue
		}
		if strings.HasPrefix(trimmed, "#### ") {
			closeList()
			out.WriteString("<h4>" + renderInline(strings.TrimPrefix(trimmed, "#### ")) + "</h4>")
			continue
		}
		if strings.HasPrefix(trimmed, "- ") || strings.HasPrefix(trimmed, "* ") {
			if !inList {
				out.WriteString("<ul>")
				inList = true
			}
			out.WriteString("<li>" + renderInline(trimmed[2:]) + "</li>")
			continue
		}
		if strings.HasPrefix(trimmed, "> ") {
			closeList()
			out.WriteString("<blockquote>" + renderInline(strings.TrimPrefix(trimmed, "> ")) + "</blockquote>")
			continue
		}

		closeList()
		out.WriteString("<p>" + renderInline(trimmed) + "</p>")
	}
	closeList()
	return out.String()
}
